### ISSUE TITLE
Subscription to mediathek topic and/or query

### ISSUE THREAD

**Issue by dennmuel** [mediathekview/zapp#176]
Would it be desirable and possible, to mark certain shows (or maybe channels) as favourites in the mediathek? Would be nice, if one could just mark the shows one is really interested in and quickly see, if there is a new entry for it in the mediathek (maybe even get a push notification, though personally I'm not a fan of those).
Could be worked around with #58, so I'm fine with waiting for the next release and see if that does it.

**Comment by cemrich** [comment]
Are you talking about individual videos or shows in the sense of "Sendung mit der Maus"? The latter we cannot filter in any meaningful way. The mediathekviewweb api returns topic and title for each video. Topic can be everything from "Die Sendung mit der Maus" to meaningless tags like "sonntags" or "Tiere". So it has (most of the time) no real value for filtering things.

However, I like the idea of "subscribing" to a search query (notifications or not).

**Comment by dennmuel** [comment]
Yes, I was talking of the latter, so I get to know, each time there's a new episode of e.g. "Sendung mit der Maus" available.

Too bad the filtering/API aren't powerful enough. I suspected something like this when filtering for videos with "Sherlock" returned both the BBC series as well as the kids show "Sherlock Yak". A kind of "show ID" would be handy, but I guess this would be considerable in the scope of developing the mvw-api-2.0.

**Comment by cemrich** [comment]
Thank you for your feedback. I will keen this ticket around but will most likely not be able to implement it in the near future.

**Comment by EvilBMP** [comment]
I think it would be nice to have the possibility to save searches as some kind of bookmarks or favorites. Like a saved search on eBay for example. That would ease things a little, so that you don't have to type the same search term each time again, if you search for different things. For example "lanz" or "maretv" or "bob ross" :-D. 

Sure the filtered list depends on the given search term of the user. For me it is not important to get a push notification for a "new" show appearing in a saved search, although that could be nice. I just would like to reduce typing ;-)

Thanks for your efforts so far...

**Comment by cemrich** [comment]
This is out of scope for Zapp for now, so I'll close this issue.

Bookmarks will be part of the upcoming release 8.0.0. For saving queries there is another issue #303
