### ISSUE TITLE
Filter / Future Shows

### ISSUE THREAD

**Issue by Bond246** [mediathekview/zapp#177]
Hallo 

Actually shows in mediathekview that will release in future are not shown in zapp. Mediathekview Web has a seperate filter option to show this mediathek items.

Examples are Terra X shows of ZDF that come online before thay are in linear tv...

It would be nice to also find future shows in zapp.
Maybe Zapp need to get a complete filter function?

Kind regards

**Comment by cemrich** [comment]
Thank you for your report! This feature does not exist in Zapp because most people won't use and/or miss it. I try to keep Zapps UI as simple as possible.

There are some more tickets regarding filter options for the mediathek list. Once these are resolved I will think about some kind of "future shows" toggle. Until then I'll close this ticket (due to low priority and to keep the backlog clean).

**Comment by klawdhfzasjhaa** [comment]
I would like to encourage you to reopen and implement this request as a (activated default) setting. I agree with about the filter options.
But I agree with @Bond246 about the future issue, which is also mentioned in #122. As people are moving away from linear TV, they wish to watch series on demand. So it would be nice to find all episodes of a series that are online at that moment, regardless if they already aired on linear TV. In fact, it's confusing to not find episodes in Zapp, that can be found on https://www.ardmediathek.de/ e. g.

**Comment by cemrich** [comment]
As mentioned above I'll focus on more important features first. Cluttering the UI with yet one more option half of the users do not understand or ever need without a broader UI concept (which is planned but out of scope right now) is not what Zapp is about. Also, it will never be a power tool with all functions and options of MediathekView available. Instead Zapp focuses on ease of use for a broad base of non-power-users.

If you want to download or watch the newest shows, please try [MediathekViewWeb](https://mediathekviewweb.de/).

**Comment by klawdhfzasjhaa** [comment]
Sorry, but what could be more important than to show all expected search results?
> half of the users do not understand or ever need

In my view, this is a wrong assumption. It should be possible for the "broad base of non-power-users" to find **all** online content. This has nothing to do with Zapp becoming a "power tool". It's a basic function.

One example: https://www.zdf.de/dokumentation/terra-x/magie-der-maerchen-frau-holle-und-ihre-versunkene-welt-100.html. "Frau Holle und ihre versunkene Welt" was aired today and will be found in Zapp. "Hänsel und Gretel auf der Spur" will be aired on 11th October and is mentioned on the above website. What is the reason for not having it in the search results in Zapp? I don't get it.

If UI clutter is an issue, than you could hard code futureItems = true.
https://mediathekviewweb.de/ is good for big screens, whereas Zapp is good for mobile..

**Comment by Bond246** [comment]
Hello,

same opinion from my side. I installed Zapp because mediathekviewweb is horrible to use from mobile. Actually without filtering it doesn't solve "my problems".

Thanks to @klawdhfzasjhaa for the passionate commitment.

**Comment by cemrich** [comment]
> If UI clutter is an issue, than you could hard code futureItems = true.

Yeah, using the most basic, easy to implement single line fix for this issue did cross my mind, but I decided against it.

> It's a basic function.

It is, once you search for a specific show. But it breaks the mediathek list big time, once a channel dumps all its 50 future show episodes at once. This does make simple browsing impossible (not always but too often). I *do not expect* a show from the far future when simply browsing for new shows ("zapping").

I will experiment with some "quick fix" ideas and look how they feel, but please do not expect a quick solution here.

**Comment by klawdhfzasjhaa** [comment]
Can you please re-open this so it's not forgotten?

**Comment by cemrich** [comment]
The filter feature is almost finished. Future shows will be always displayed.

**Comment by cemrich** [comment]
Fixed in 6.0.0

**Comment by klawdhfzasjhaa** [comment]
Thank you very much! Have nice Christmas time!

**Comment by rstruminski** [comment]
Sorry, but I completely disagree with the way it has been done now. Before the update, I used to open Zapp and quickly find the most recently aired programs. It was easy to see what interesting things I had "missed" on TV today.

Now the first - I don't know - _hundreds_ of entries are always the same, starting from some show airing in 2031(!) and working their way backwards to 2021. I can no longer simply scroll down to see what was on TV earlier today, except by scrolling down a _bazillion_ of entries until I reach 2021.

This almost renders Zapp useless for me - I am force to use mediathekviewweb.de again, because at least I can toggle future shows off there.

Please make this a toggle/filter like on mediathekviewweb.de. Ideally a filter that saves its last state, so future shows stay hidden the next time Zapp is opened.

**Comment by rstruminski** [comment]
Also, Zapp used to suggest the last ~20 search terms before the update. This was very handy, because you often repeat the same searches (i. e. "Heute Journal vom").

Now you have to retype everything every time, there's no way to make a "search shortcut" any more.
