### ISSUE TITLE
Add sleep timer

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#194]
> A sleeptimer would be a nice feature like in tvs, so you dont sleep away peacefully while a space documentary and wake up with WW2 and gunfire

**Comment by bjacke** [comment]
A sleep timer woult be really really nice.

A slightly more sophisticated idea: stop playing shortly after the current broadcast finished. "Zapp" know when the current broadcast finishes because it always knows about the current name of the running broadcast, so shortly afer that changes, it might stop playing.

**Comment by kojid0** [comment]
I like the mentioned idea but it would be a good first step to introduce a "basic" timer as a base while we can discuss further improvements afterwards

**Comment by cemrich** [comment]
Thanks to @Bnyro I implemented a timer inspired by Antenna Pod. It will be available in the next release.

**Comment by cemrich** [comment]
This feature has been added in 8.3.0
