### ISSUE TITLE
Live stream [arte] does not work

### ISSUE THREAD

**Issue by justf0rfun** [mediathekview/zapp#243]
## Which channel does not work correctly?
arte DE

## What is the problem?
- [x] does not load at all
- [ ] shows always the same looping content
- [ ] performance problem (stuttering or other)
- [ ] other problem (add description)

On a desktop PC I opened the firefox developer tools and the 720p stream seems to has the URL:
https://artesimulcast.akamaized.net/hls/live/2030993/artelive_de/master_v720.m3u8

By the way: This is not the first time that I reported a non working stream and the last time it was fixed without having to update the app. A short explanation would be useful how the app works. I guess it fetches a list of streams from a central server. Where can I find that list? So that I can compare the streaming URLs that the app uses to the current streaming URLs that the browser uses.

Thanks in advance.

**Comment by cemrich** [comment]
Thank you very much for your feedback!

Zapp fetches its program info and channel urls from a lean node.js backend: https://github.com/mediathekview/zapp-backend The channel info list can be found at https://github.com/mediathekview/zapp-backend/blob/master/models/channelInfoList.js

I implemented the channel url mechanism because the stream urls tend to change about twice a year and app updates can take quite a while before they reach all users.

In MediathekView itself there is a list of streaming urls too: https://github.com/mediathekview/MServer/blob/master/dist/live-streams.json
