### ISSUE TITLE
Live stream subtitles of Das Erste does not work

### ISSUE THREAD

**Issue by strelitzer** [mediathekview/zapp#282]
## Which channel does not work correctly?
Das Erste (ARD)

## What is the problem?
**Live stream subtitles** of channel _Das Erste_ no longer work at all. Tatort, Tagesschau and so on - no subtitles. **CC** button offers only "Unknown"/"Unbekannt".

Mediathek versions of shows work as expected, with subtitles.

No problems with subtitles with ARD Mediathek app.

**Comment by cemrich** [comment]
Thank you very much for your bug report and sorry for the late feedback. 

Sadly ARD decided to burn their subtitles into a special video stream instead of providing a subtitle layer in addition to the video stream. There is no easy fix for Zapp, so it will remain this way until subtitles are privided the "proper" way again.

**Comment by strelitzer** [comment]
Thank you for your explanation. Unfortunately, I have not noticed this (badly) change.

**Comment by strelitzer** [comment]
> Sadly ARD decided to burn their subtitles into a special video stream instead of providing a subtitle layer in addition to the video stream.

It does not seem to be a general problem of the ARD. Most (all?) "third programs" of the ARD provides subtitles which are usable with Zapp.
_phoenix_ (ARD/ZDF), _one_ (ARD), and _alpha_ (ARD/BR) has subtitles – also in Zapp.

**Comment by strelitzer** [comment]
@cemrich The subtitles of Das Erste are back. I only noticed it today because I had mostly used the ARD Mediathek app. Did you solve the problem with one of the 7s releases?
