### ISSUE TITLE
Live stream of SR Fernsehen does not work

### ISSUE THREAD

**Issue by strelitzer** [mediathekview/zapp#315]
## Which channel does not work correctly?
SR Fernsehen

## What is the problem?
- [x] does not load at all
- [ ] shows always the same looping content
- [ ] performance problem (stuttering or other)
- [ ] other problem (add description)

EPG works correctly.

**Comment by justf0rfun** [comment]
I think the new URL one of these:

https://srfs.akamaized.net/hls/live/689649/srfsgeo/master-720p-3328.m3u8
https://srfs.akamaized.net/hls/live/689649/srfsgeo/index.m3u8

I guess the first one explicitly specifies the resolution. Not sure if the second one can vary in resolution. In my browser it probably refers to the first URL. I did not dive into the m3u9 files. I hate that stuff because IIRC it is poorly specified / standardized (as so many other things :/  ).

I think the new URLs must go there:
https://github.com/mediathekview/zapp-backend/blob/master/models/channelInfoList.js

**Comment by cemrich** [comment]
Thank you very much for this report!

The url is fixed and should be live in a few hours after a restart of zapp.

**Comment by cemrich** [comment]
And it's live!
